CREATE TABLE IF NOT EXISTS Country (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE,
    Value INTEGER NOT NULL UNIQUE,
    HasCity INTEGER,
    CurrencyId INTEGER,
    FOREIGN KEY (CurrencyId) REFERENCES Currency(Id)
)